CREATE DATABASE ESTACIONAMENTO

CREATE TABLE VALUEHOUR
(
	ID INT IDENTITY PRIMARY KEY NOT NULL,
	VALUE DECIMAL(10,2) NULL,
	TIME TIME NULL
	
)

CREATE TABLE CLIENTE
(
	ID INT IDENTITY PRIMARY KEY NOT NULL,
	NAME VARCHAR(100) NULL,
	CAR VARCHAR(100) NULL,
	PLATE VARCHAR(10) NULL,
	STATUS SMALLINT NULL DEFAULT 0,
	TIMEIN DATETIME2 NULL,
	TIMEOUT DATETIME2 NULL,
)

CREATE TABLE LOG
(
	ID INT IDENTITY PRIMARY KEY NOT NULL,
	IDCLIENTE INT NOT NULL,
	NAME VARCHAR(100) NULL,
	CAR VARCHAR(100) NULL,
	PLATE VARCHAR(10) NULL,
	TIMEIN DATETIME2 NULL,
	TIMEOUT DATETIME2 NULL,
)